<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>

<body>
<p align="justify"><strong><img src="Image/Valentino_Rossi_2010_Qatar.jpg" width="169" height="242" hspace="15" align="left" />Valentino Rossi</strong>&nbsp;(lahir di&nbsp;<a href="https://id.wikipedia.org/wiki/Urbino" title="Urbino">Urbino</a>,&nbsp;<a href="https://id.wikipedia.org/wiki/Italia" title="Italia">Italia</a>,&nbsp;<a href="https://id.wikipedia.org/wiki/16_Februari" title="16 Februari">16 Februari</a>&nbsp;<a href="https://id.wikipedia.org/wiki/1979" title="1979">1979</a>; umur 42 tahun) adalah seorang pembalap di kejuaraan grandprix motor dunia setelah era&nbsp;<a href="https://id.wikipedia.org/wiki/Michael_Doohan" title="Michael Doohan">Michael Doohan</a>, dengan titel juara dunia di empat kelas yang berbeda yang diraihnya dalam waktu tujuh tahun berkarier.Ia adalah salah seorang pembalap tersukses sepanjang masa, dengan 7 gelar juara dunia di kelas puncak (500cc/MotoGP) dan dua gelar di kelas 250cc dan 125cc. Menurut majalah olah raga terbitan Amerika, Sports Ilustrated, Rossi adalah salah satu olahragawan bergaji terbesar di duunia, ia diperkirakan digaji $34 juta pada 2007. Putra dari mantan pembalap GP 250 cc&nbsp;<a href="https://id.wikipedia.org/wiki/Graziano_Rossi" title="Graziano Rossi">Graziano Rossi</a>&nbsp;dan&nbsp;<a href="https://id.wikipedia.org/w/index.php?title=Stefania_Palma&amp;action=edit&amp;redlink=1" title="Stefania Palma (halaman belum tersedia)">Stefania Palma</a>&nbsp;ini memegang banyak rekor dan prestasi yang diraihnya melampaui banyak seniornya. Total pembalap eksentrik ini membukukan 9 gelar juara dunia, sekali di kelas 125cc pada tahun 1997, sekali di kelas 250cc (1999), dan tujuh kali juara dunia di kelas puncak 500cc/MotoGP (2001, 2002, 2003, 2004, 2005, 2008 dan 2009).</p>
<p align="justify">Setelah ayahnya, Graziano Rossi, Rossi memulai balapan di Grand Prix pada 1996 untuk Aprilia di antara 125 cc kategori dan memenangkan Kejuaraan Dunia pertama tahun berikutnya. Dari sana, ia pindah ke kategori 250cc dengan Aprilia dan memenangkan 250cc Kejuaraan Dunia pada tahun 1999. Ia memenangkan Kejuaraan Dunia 500cc dengan Honda pada tahun 2001, Kejuaraan Dunia MotoGP (juga dengan Honda) pada tahun 2002 dan 2003, dan melanjutkan kemenangan beruntunnya dengan memenangkan kejuaraan dunia 2004 dan 2005, setelah meninggalkan Honda untuk bergabung dengan Yamaha, sebelum merebut kembali gelar pada 2008 dan mempertahankannya pada tahun 2009.</p>
<p align="justify">Rossi adalah yang pertama dalam klasemen terbanyak memenangkan perlombaan dalam sejarah 500 cc / MotoGP, dengan 79 kemenangan, dan kedua di sepanjang masa menang klasemen keseluruhan dengan 105 menang balapan (di belakang Giacomo Agostini dengan 122). Rossi, bersama&nbsp;<a href="https://id.wikipedia.org/wiki/Jimmie_Johnson" title="Jimmie Johnson">Jimmie Johnson</a>&nbsp;(<a href="https://id.wikipedia.org/wiki/NASCAR" title="NASCAR">NASCAR</a>),&nbsp;<a href="https://id.wikipedia.org/wiki/Michael_Schumacher" title="Michael Schumacher">Michael Schumacher</a>&nbsp;(<a href="https://id.wikipedia.org/wiki/F1" title="F1">F1</a>) dan&nbsp;<a href="https://id.wikipedia.org/wiki/Sebastien_Loeb" title="Sebastien Loeb">Sebastien Loeb</a>(<a href="https://id.wikipedia.org/wiki/World_Rally_Championship" title="World Rally Championship">WRC</a>), juga banyak disebut orang sebagai salah satu legenda olahraga otomotif di awal&nbsp;<a href="https://id.wikipedia.org/wiki/Abad_21" title="Abad 21">Abad 21</a>.</p>
<p align="justify">Dalam perjalanan balapnya rossi, kerap berganti julukan dan melakukan hal-hal yang menarik perhatian dan menghibur. Ia beralasan bahwa semuanya itu dilakukan dimulai dengan niat bersenang-senang dan melakukan sesuatu yang lucu.</p>
<p align="justify"><strong>Rossifumi</strong>&nbsp;Julukan Rossi yang diciptakan oleh temannya saat Rossi membalap di kelas 125cc julukan ini tercipta karena Rossi kagum dengan pembalap Jepang yang khas dengan rambut panjangnya,&nbsp;<a href="https://id.wikipedia.org/wiki/Norick_Abe" title="Norick Abe">Norick Abe</a>&nbsp;yang saat itu berumur 17 tahun dan dengan gigih bertarung dengan Michael Doohan dan&nbsp;<a href="https://id.wikipedia.org/wiki/Kevin_Scwantz" title="Kevin Scwantz">Kevin Scwantz</a>&nbsp;dikelas 500cc, karena nama asli pembalap Jepang itu Norifumi Abe maka Rossi dijuluki Rossifumi.Tahun 2004 Rossi dan Abe sama-sama membela Yamaha berada dalam beda tim namun satu grafis,yaitu dominasi warna biru.Rossi berada di tim Gauloises Fortuna Yamaha Team sedangkan Abe bernaung di Fortuna Gauloises Tech 3 Yamaha Team.</p>
<p align="justify"><strong>Valentinik</strong>&nbsp;Julukan ini berasal dari tokoh kartun Daffy Duck yang menjadi superhero yang di Italia bernama Paperinik. Julukan ini dipakainya pada saat membalap di kelas 250cc.</p>
<p align="justify"><strong>The Doctor</strong>&nbsp;Setelah naik ke kelas 500cc pada musim 2000 Rossi menjuluki dirinya dengan The Doctor karena membalap di kelas 500cc butuh keseriusan dan ia merasa dirinya bukan anak kecil lagi, selain itu ia juga menyukai ide sebagi illmuwan gila dan melakukan eksperimen gila, ia menganggap pantas memakai julukan itu setelah mendapatkan prestasi sebagai juara dunia.&rdquo;Di balap 500cc kita tidak butuh superhero. Yang kita perlukan cuma tenang, kalem, dan pemikir seperti doktor,&rdquo;ucapnya. Disamping itu, nama Valentino di Italia kebanyakan digunakan oleh para doktor. Ia juga mulai mengurangi perayaan kemenangan yang dianggapnya sudah tak pantas ia lakukan. &ldquo;Cukup dengan melambai seperti pembalap lain, lalu malamnya pesta habis-habisan bareng sahabat-sahabat saya.&rdquo;</p>
<p align="justify">&nbsp;</p>
</body>
</html>
